### ISSUE TITLE
A problem regarding testing the model on kitti dataset

### ISSUE THREAD

**Issue by SimonSongg** [hlwang1124/SNE-RoadSeg#19]
Hello, I try to run "run_example.py" to test it on the image in the test dataset and it works very well. Great work!! But when I tried to run "test.py", an error appeared.

---------- Networks initialized -------------
[Network RoadSeg] Total number of parameters : 201.325 M
-----------------------------------------------
Traceback (most recent call last):
  File "test.py", line 31, in <module>
    for i, data in enumerate(dataset):
  File "C:\Users\sf995\iCloudDrive\DL\SNE-RoadSeg\data\__init__.py", line 71, in __iter__
    for i, data in enumerate(self.dataloader):
  File "D:\anaconda\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 193, in __iter__
    return _DataLoaderIter(self)
  File "D:\anaconda\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 469, in __init__
    w.start()
  File "D:\anaconda\envs\pytorch\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "D:\anaconda\envs\pytorch\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\anaconda\envs\pytorch\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\anaconda\envs\pytorch\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\anaconda\envs\pytorch\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'CustomDatasetDataLoader.initialize.<locals>.<lambda>'

(pytorch) C:\Users\sf995\iCloudDrive\DL\SNE-RoadSeg>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\anaconda\envs\pytorch\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\anaconda\envs\pytorch\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

Seems like it is about the lambda function. Could you help me?

**Comment by hlwang1124** [comment]
Hi, @SimonSongg .
It seems like a problem on Windows. I have found two possible solutions. [One](https://discuss.pytorch.org/t/cant-pickle-local-object-dataloader-init-locals-lambda/31857/9) is to replace the lambda function in `Line62` of `data/__init__.py`, [the other one](https://github.com/rusty1s/pytorch_geometric/issues/366) is to set `num_workers=0`. Hope this can help you address this problem.

**Comment by SimonSongg** [comment]
Many thanks! Problem solved with a new errror xD. I will figure it out. Thank you again. Happy new year.

**Comment by SimonSongg** [comment]
> Hi, @SimonSongg .
> It seems like a problem on Windows. I have found two possible solutions. [One](https://discuss.pytorch.org/t/cant-pickle-local-object-dataloader-init-locals-lambda/31857/9) is to replace the lambda function in `Line62` of `data/__init__.py`, [the other one](https://github.com/rusty1s/pytorch_geometric/issues/366) is to set `num_workers=0`. Hope this can help you address this problem.

Just completely solved, results from the path format difference between linux and windows. Nice work! Thank you again for your reply.

**Comment by hlwang1124** [comment]
Glad to hear that! Happy Chinese New Year!
