### ISSUE TITLE
No such file 'latest_net_RoadSeg.pth'

### ISSUE THREAD

**Issue by smoftsky** [hlwang1124/SNE-RoadSeg#45]
From where i can download it？

**Comment by smoftsky** [comment]
model [RoadSegModel] was created
loading the model from ./checkpoints\experiment_name\latest_net_RoadSeg.pth
Traceback (most recent call last):

  File "C:\Users\13191\Desktop\SNE-RoadSeg-master\test.py", line 24, in <module>
    model.setup(opt)

  File "C:\Users\13191\Desktop\SNE-RoadSeg-master\models\base_model.py", line 41, in setup
    self.load_networks(opt.epoch)

  File "C:\Users\13191\Desktop\SNE-RoadSeg-master\models\base_model.py", line 137, in load_networks
    state_dict = torch.load(load_path, map_location=str(self.device))

  File "C:\Users\13191\Anaconda2\envs\tensorflow\lib\site-packages\torch\serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:

  File "C:\Users\13191\Anaconda2\envs\tensorflow\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)

  File "C:\Users\13191\Anaconda2\envs\tensorflow\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))

FileNotFoundError: [Errno 2] No such file or directory: './checkpoints\\experiment_name\\latest_net_RoadSeg.pth'

**Comment by hlwang1124** [comment]
Hi, @smoftsky . As mentioned in README, the pretrained weights `kitti_net_RoadSeg.pth` for our SNE-RoadSeg-152 can be downloaded from [here](https://drive.google.com/file/d/17eqDPTs0Sv83Q7e-IWox_69bCbiXUzPU/view?usp=sharing).
